[package]
name = "markplus"
version = "0.1.0"
edition = "2024"

[lib]
name = "markplus_hx"
crate-type = [ "cdylib" ]

[dependencies]
abi_stable = "0.11.3"
regex = "1.11.1"
steel-core = { version = "0.7.0", features = [ "dylibs", "sync" ] }
steel-derive = { version = "0.6.0" }
